package sudoku

type Technique int

// iota acts as counter that increases by one on each line, starting at 0
const (
	TechniqueNakedSingle Technique = iota
	TechniqueHiddenSingle
	TechniqueNakedPair
	TechniqueHiddenPair
)

type LogicSolveResult struct {
	Start             Board
	Progress          Board
	valid             bool
	solvedByLogic     bool // false for already solved board
	nakedSingleCount  int
	hiddenSingleCount int
	nakedPairCount    int
	hiddenPairCount   int
	MaxTechnique      Technique
	rounds            int
}

func NewResult() LogicSolveResult {
	return LogicSolveResult{}
}

// This takes a board (i.e. puzzle generated by GeneratePuzzle) and tries to solve it with h
func SolveByLogic(b Board) LogicSolveResult {

	puzzle := b
	result := NewResult()
	result.Start = puzzle

	if !b.IsValid() {
		result.valid = false
		return result
	}

	result.valid = true
	result.MaxTechnique = TechniqueNakedSingle
	puzzle.UpdateCandidates()

	for !puzzle.IsSolved() {
		progress := false

		for puzzle.ApplyNakedSingle() {
			progress = true
			result.nakedSingleCount++
		}

		for puzzle.ApplyHiddenSingle() {
			progress = true
			result.hiddenSingleCount++
			// can it be avoided to run this on every iteration of the loop?
			if TechniqueHiddenSingle > result.MaxTechnique {
				result.MaxTechnique = TechniqueHiddenSingle
			}
		}

		for puzzle.ApplyNakedPair() {
			progress = true
			result.nakedPairCount++
			if TechniqueNakedPair > result.MaxTechnique {
				result.MaxTechnique = TechniqueNakedPair
			}
		}

		for puzzle.ApplyHiddenPair() {
			progress = true
			result.hiddenPairCount++
			if TechniqueHiddenPair > result.MaxTechnique {
				result.MaxTechnique = TechniqueHiddenPair
			}
		}

		if !progress {
			break
		}
		result.rounds++
		result.solvedByLogic = puzzle.IsSolved()
	}

	result.Progress = puzzle
	return result
}
