package sudoku

type Technique int

// iota acts as counter that increases by one on each line, starting at 0
const (
	TechniqueNakedSingle Technique = iota
	TechniqueHiddenSingle
	TechniqueNakedPair
	TechniqueHiddenPair
	TechniquePointing
	TechniqueNakedTriple
)

type LogicSolveResult struct {
	Start             Board
	Progress          Board
	valid             bool
	solvedByLogic     bool // false for already solved board
	nakedSingleCount  int
	hiddenSingleCount int
	nakedPairCount    int
	hiddenPairCount   int
	pointingCount     int
	nakedTripleCount  int
	MaxTechnique      Technique
	rounds            int
}

func NewResult() LogicSolveResult {
	return LogicSolveResult{}
}

// This takes a board (i.e. puzzle generated by GeneratePuzzle) and tries to solve it with h
func SolveByLogic(b Board) LogicSolveResult {

	puzzle := b
	result := NewResult()
	result.Start = puzzle

	if !b.IsValid() {
		result.valid = false
		return result
	}

	result.valid = true
	result.MaxTechnique = TechniqueNakedSingle
	puzzle.UpdateCandidates()

	for !puzzle.IsSolved() {
		progress := false

		for puzzle.ApplyNakedSingles() {
			progress = true
			result.nakedSingleCount++
		}

		for puzzle.ApplyHiddenSingles() {
			progress = true
			result.hiddenSingleCount++
			if TechniqueHiddenSingle > result.MaxTechnique {
				result.MaxTechnique = TechniqueHiddenSingle
			}
		}

		for {
			applied, n := puzzle.ApplyNakedPairs()
			if !applied {
				break
			}
			progress = true
			result.nakedPairCount += n
			if TechniqueNakedPair > result.MaxTechnique {
				result.MaxTechnique = TechniqueNakedPair
			}
		}

		for {
			applied, n := puzzle.ApplyHiddenPairs()
			if !applied {
				break
			}
			progress = true
			result.hiddenPairCount += n
			if TechniqueHiddenPair > result.MaxTechnique {
				result.MaxTechnique = TechniqueHiddenPair
			}
		}

		for {
			applied, n := puzzle.ApplyPointings()
			if !applied {
				break
			}
			progress = true
			result.pointingCount += n
			if TechniquePointing > result.MaxTechnique {
				result.MaxTechnique = TechniquePointing
			}
		}

		for {
			applied, n := puzzle.ApplyNakedTriples()
			if !applied {
				break
			}
			progress = true
			result.nakedTripleCount += n
			if TechniqueNakedTriple > result.MaxTechnique {
				result.MaxTechnique = TechniqueNakedTriple
			}
		}

		if !progress {
			break
		}
		result.rounds++
		result.solvedByLogic = puzzle.IsSolved()
	}

	result.Progress = puzzle
	return result
}
